// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cs.proto

package cs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ID int32

const (
	ID_ID_C2S_Hello ID = 10000
	ID_ID_S2C_Hello ID = 10001
)

var ID_name = map[int32]string{
	10000: "ID_C2S_Hello",
	10001: "ID_S2C_Hello",
}

var ID_value = map[string]int32{
	"ID_C2S_Hello": 10000,
	"ID_S2C_Hello": 10001,
}

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}

func (x ID) String() string {
	return proto.EnumName(ID_name, int32(x))
}

func (x *ID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ID_value, data, "ID")
	if err != nil {
		return err
	}
	*x = ID(value)
	return nil
}

func (ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{0}
}

type C2S_Hello struct {
	Id                   *uint32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_Hello) Reset()         { *m = C2S_Hello{} }
func (m *C2S_Hello) String() string { return proto.CompactTextString(m) }
func (*C2S_Hello) ProtoMessage()    {}
func (*C2S_Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{0}
}

func (m *C2S_Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_Hello.Unmarshal(m, b)
}
func (m *C2S_Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_Hello.Marshal(b, m, deterministic)
}
func (m *C2S_Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_Hello.Merge(m, src)
}
func (m *C2S_Hello) XXX_Size() int {
	return xxx_messageInfo_C2S_Hello.Size(m)
}
func (m *C2S_Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_Hello proto.InternalMessageInfo

func (m *C2S_Hello) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *C2S_Hello) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type S2C_Hello struct {
	Ret                  *uint32  `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_Hello) Reset()         { *m = S2C_Hello{} }
func (m *S2C_Hello) String() string { return proto.CompactTextString(m) }
func (*S2C_Hello) ProtoMessage()    {}
func (*S2C_Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_af7bf51985781725, []int{1}
}

func (m *S2C_Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_Hello.Unmarshal(m, b)
}
func (m *S2C_Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_Hello.Marshal(b, m, deterministic)
}
func (m *S2C_Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_Hello.Merge(m, src)
}
func (m *S2C_Hello) XXX_Size() int {
	return xxx_messageInfo_S2C_Hello.Size(m)
}
func (m *S2C_Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_Hello proto.InternalMessageInfo

func (m *S2C_Hello) GetRet() uint32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *S2C_Hello) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("cs.ID", ID_name, ID_value)
	proto.RegisterType((*C2S_Hello)(nil), "cs.C2S_Hello")
	proto.RegisterType((*S2C_Hello)(nil), "cs.S2C_Hello")
}

func init() { proto.RegisterFile("cs.proto", fileDescriptor_af7bf51985781725) }

var fileDescriptor_af7bf51985781725 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x2e, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4a, 0x2e, 0x56, 0xd2, 0xe5, 0xe2, 0x74, 0x36, 0x0a, 0x8e,
	0xf7, 0x48, 0xcd, 0xc9, 0xc9, 0x17, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd2,
	0xe0, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0x60, 0x52, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0xf4, 0xb9, 0x38, 0x83, 0x8d, 0x9c, 0xa1, 0xca, 0x05, 0xb8,
	0x98, 0x8b, 0x52, 0x4b, 0xa0, 0xea, 0x41, 0x4c, 0x4c, 0x0d, 0x5a, 0x5a, 0x5c, 0x4c, 0x9e, 0x2e,
	0x42, 0x82, 0x5c, 0x3c, 0x9e, 0x2e, 0xf1, 0x70, 0x8b, 0x04, 0x26, 0xf8, 0x41, 0x85, 0xe0, 0x86,
	0x09, 0x4c, 0xf4, 0x03, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x5a, 0x76, 0xb8, 0x9a, 0x00, 0x00,
	0x00,
}
